Replaced staging basic example URL with relative URL
prevwong/craft.js pull request #187
Opened 2021-02-12 08:29 UTC by ankri

Currently when netlify is hosting the PR preview the URL for the basic example will link to the production example. This should fix that by providing a relative link.

Would it be possible to configure Netlify in a way, that they not only post the URL of the landing example, but also the basic example in their comment?

2021-02-18 04:47 UTC, prevwong commented on config.js
>        DOCUMENTATION: 'https://craftjs.netlify.com/r/docs/overview/',
Can we change these too?

2021-02-18 04:48 UTC, prevwong requested changes
Thanks!

2021-02-18 09:50 UTC, ankri commented on config.js
>        DOCUMENTATION: 'https://craftjs.netlify.com/r/docs/overview/',
Done 👍

2021-02-18 09:51 UTC, prevwong approved these changes

2021-11-15 12:27 UTC, prevwong commented
Closing since this is not needed anymore since we refactored our docusaurus site structure

2021-11-15 12:27 UTC, closed without merging