Update peerDependency on React to >= 16.8
prevwong/craft.js pull request #307
Opened 2021-09-10 20:14 UTC by jhensley

2021-09-13 16:16 UTC, prevwong commented
Hi @jhensley, could you update the React version of the other packages as well? (ie: layers and utils)

2021-09-13 16:22 UTC, jhensley commented
@prevwong done, good call.

2021-09-14 09:07 UTC, prevwong requested changes

2021-09-14 09:07 UTC, prevwong commented on packages/layers/package.json
> +    "react": ">=16.8.0"
Missed a comma here

2021-09-14 15:50 UTC, prevwong approved these changes
Thanks!

2021-09-14 15:50 UTC, merged