fix: correct URLs in README
prevwong/craft.js pull request #371
Opened 2022-02-07 10:11 UTC by dxcqcv

2022-02-08 07:42 UTC, Shaddix commented
Fixes #370

2022-02-08 08:14 UTC, dxcqcv commented
> Fixes #370

I still cannot visit URLs in README.md

![when I visited these URLs I got 404 pages](https://res.cloudinary.com/daxmegjiv/image/upload/v1644307975/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE_2022-02-08_160021_krcwgp.png)

2022-02-10 17:22 UTC, prevwong requested changes

2022-02-10 17:22 UTC, prevwong commented on packages/core/README.md
> +  - However, you could still consider using the [examples](https://github.com/dxcqcv/craft.js/tree/develop/examples) as a starting point.
```suggestion
  - However, you could still consider using the [examples](https://github.com/prevwong/craft.js/tree/develop/examples) as a starting point.
```

2024-05-18 11:18 UTC, closed without merging